/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3D/Character.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { createPortal } from '@react-three/fiber'
export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3D/Character.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=> {
    console.log(actions);
    actions["Armature|mixamo.com|Layer0"].play();
    console.log(nodes)
  })
  return (
    <>
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MocapGuy_HiRes_Meshes" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>

          <primitive object={nodes.mixamorigHips} />
          <group name="MocapGuy_Body">
            <skinnedMesh name="MocapGuy_Body_1" geometry={nodes.MocapGuy_Body_1.geometry} material={materials.Body_MAT} skeleton={nodes.MocapGuy_Body_1.skeleton} />
            <skinnedMesh name="MocapGuy_Body_2" geometry={nodes.MocapGuy_Body_2.geometry} material={materials.Reflectors} skeleton={nodes.MocapGuy_Body_2.skeleton} />
          </group>
          <skinnedMesh name="MocapGuy_BrowsLashes" geometry={nodes.MocapGuy_BrowsLashes.geometry} material={materials.Brows_MAT} skeleton={nodes.MocapGuy_BrowsLashes.skeleton} />
          <skinnedMesh name="MocapGuy_Caruncula" geometry={nodes.MocapGuy_Caruncula.geometry} material={materials.Body_MAT} skeleton={nodes.MocapGuy_Caruncula.skeleton} />
          <skinnedMesh name="MocapGuy_Eyes" geometry={nodes.MocapGuy_Eyes.geometry} material={materials.Eyes_MAT} skeleton={nodes.MocapGuy_Eyes.skeleton} >
          </skinnedMesh>
          <group name="MocapGuy_Hat">
            <skinnedMesh name="MocapGuy_Hat_1" geometry={nodes.MocapGuy_Hat_1.geometry} material={materials.Body_MAT} skeleton={nodes.MocapGuy_Hat_1.skeleton} />
            <skinnedMesh name="MocapGuy_Hat_2" geometry={nodes.MocapGuy_Hat_2.geometry} material={materials.Reflectors} skeleton={nodes.MocapGuy_Hat_2.skeleton} />
          </group>
          <skinnedMesh name="MocapGuy_Teeth" geometry={nodes.MocapGuy_Teeth.geometry} material={materials.Body_MAT} skeleton={nodes.MocapGuy_Teeth.skeleton} />
        </group>
      </group>
    </group>
    {createPortal(props.children, nodes.mixamorigHeadTop_End)}

    </>

  )
}

useGLTF.preload('/3D/Character.glb')
