/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3D/Hat.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hat(props) {
  const { nodes, materials } = useGLTF('/3D/Hat.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cap_LowPoly.geometry} material={materials['Material.001']} position={[0.004, 0.021, 0.028]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[0, 0.249, 0.557]} rotation={[1.129, 0, 0]} scale={[0.262, 0.062, 0.058]} />
    </group>
  )
}

useGLTF.preload('/3D/Hat.glb')
